print("SHRI GANESHAYA NAMAH")
print("Demonstration of SET")
Marvellous = {21,"PPA",30,3.09,"PYTHON"}
print(Marvellous)
print(len(Marvellous))
Marvellous.remove(3.09)
print(Marvellous)
Marvellous.discard(21)
print(Marvellous)
Marvellous.add("Angular")
print(Marvellous)
