print("SHRI GANESHAYA NAMAH")
print("Demonstration of tuples")
tup = (3,"Marvellous",21,"infosystems",3.14)
print(tup)
print(tup[0])
print(tup[1])
print(tup[2])
print(tup[3])
print(tup[4])
print(len(tup))
print("Marvellous" in tup)
del tup